//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeitManager.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeitManager.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        internal static string TimerDurationInvalid {
            get {
                return ResourceManager.GetString("TimerDurationInvalid", resourceCulture);
            }
        }
        internal static string TimerEmptyHint {
            get {
                return ResourceManager.GetString("TimerEmptyHint", resourceCulture);
            }
        }
        internal static string CreateTimerButton {
            get {
                return ResourceManager.GetString("CreateTimerButton", resourceCulture);
            }
        }
        internal static string StopwatchEmptyHint {
            get {
                return ResourceManager.GetString("StopwatchEmptyHint", resourceCulture);
            }
        }
        internal static string StreakDays {
            get {
                return ResourceManager.GetString("StreakDays", resourceCulture);
            }
        }
        internal static string NextAlarmIn {
            get {
                return ResourceManager.GetString("NextAlarmIn", resourceCulture);
            }
        }
        internal static string NextAlarmCountdownFormat {
            get {
                return ResourceManager.GetString("NextAlarmCountdownFormat", resourceCulture);
            }
        }
        internal static string NewAlarmButton {
            get {
                return ResourceManager.GetString("NewAlarmButton", resourceCulture);
            }
        }
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        internal static string OnboardingQuickTimer {
            get {
                return ResourceManager.GetString("OnboardingQuickTimer", resourceCulture);
            }
        }
        internal static string OnboardingCreateTimer {
            get {
                return ResourceManager.GetString("OnboardingCreateTimer", resourceCulture);
            }
        }
    }
}
