using System.Collections.Generic;

namespace HandwerkerImperium.Domain.Achievements
{
    /// <summary>
    /// Vordefinierte Achievements (Gameplay-Werte). 1:1-Port aus dem Avalonia-Original
    /// (Models/Achievement.cs Achievements.GetAll() — 109 Einträge). Nur Gameplay-Felder
    /// (Id/Category/TargetValue/Rewards); Title/Description/Icon (Lokalisierung + Emoji/Material-Icon)
    /// liefert die Unity-Präsentationsschicht. Werte per Skript aus dem Original extrahiert (kein Tippfehler-Risiko).
    /// </summary>
    public static class Achievements
    {
        public static List<Achievement> GetAll()
        {
            return new List<Achievement>
            {
                new Achievement { Id = "first_order", Category = AchievementCategory.Orders, TargetValue = 1, MoneyReward = 100, XpReward = 10 },
                new Achievement { Id = "orders_10", Category = AchievementCategory.Orders, TargetValue = 10, MoneyReward = 500, XpReward = 25 },
                new Achievement { Id = "orders_50", Category = AchievementCategory.Orders, TargetValue = 50, MoneyReward = 2500, XpReward = 150, GoldenScrewReward = 10 },
                new Achievement { Id = "orders_100", Category = AchievementCategory.Orders, TargetValue = 100, MoneyReward = 5000, XpReward = 300, GoldenScrewReward = 25 },
                new Achievement { Id = "orders_500", Category = AchievementCategory.Orders, TargetValue = 500, MoneyReward = 25000, XpReward = 750 },
                new Achievement { Id = "perfect_first", Category = AchievementCategory.MiniGames, TargetValue = 1, MoneyReward = 200, XpReward = 15 },
                new Achievement { Id = "perfect_10", Category = AchievementCategory.MiniGames, TargetValue = 10, MoneyReward = 1000, XpReward = 75 },
                new Achievement { Id = "perfect_50", Category = AchievementCategory.MiniGames, TargetValue = 50, MoneyReward = 5000, XpReward = 250 },
                new Achievement { Id = "streak_5", Category = AchievementCategory.MiniGames, TargetValue = 5, MoneyReward = 500, XpReward = 30 },
                new Achievement { Id = "streak_10", Category = AchievementCategory.MiniGames, TargetValue = 10, MoneyReward = 2000, XpReward = 150 },
                new Achievement { Id = "games_100", Category = AchievementCategory.MiniGames, TargetValue = 100, MoneyReward = 2500, XpReward = 150 },
                new Achievement { Id = "workshop_level10", Category = AchievementCategory.Workshops, TargetValue = 10, MoneyReward = 1000, XpReward = 50 },
                new Achievement { Id = "workshop_level25", Category = AchievementCategory.Workshops, TargetValue = 25, MoneyReward = 5000, XpReward = 150 },
                new Achievement { Id = "all_workshops", Category = AchievementCategory.Workshops, TargetValue = 6, MoneyReward = 2500, XpReward = 200 },
                new Achievement { Id = "worker_first", Category = AchievementCategory.Workshops, TargetValue = 1, MoneyReward = 100, XpReward = 10 },
                new Achievement { Id = "workers_10", Category = AchievementCategory.Workshops, TargetValue = 10, MoneyReward = 1000, XpReward = 75 },
                new Achievement { Id = "workers_25", Category = AchievementCategory.Workshops, TargetValue = 25, MoneyReward = 5000, XpReward = 250, GoldenScrewReward = 15 },
                new Achievement { Id = "workshop_level50", Category = AchievementCategory.Workshops, TargetValue = 50, MoneyReward = 50000, XpReward = 500 },
                new Achievement { Id = "workshop_level100", Category = AchievementCategory.Workshops, TargetValue = 100, MoneyReward = 200_000, XpReward = 1000, GoldenScrewReward = 30 },
                new Achievement { Id = "workshop_level250", Category = AchievementCategory.Workshops, TargetValue = 250, MoneyReward = 1_000_000, XpReward = 2500, GoldenScrewReward = 50 },
                new Achievement { Id = "workshop_level500", Category = AchievementCategory.Workshops, TargetValue = 500, MoneyReward = 5_000_000, XpReward = 5000, GoldenScrewReward = 100 },
                new Achievement { Id = "workshop_level1000", Category = AchievementCategory.Workshops, TargetValue = 1000, MoneyReward = 50_000_000, XpReward = 12500, GoldenScrewReward = 250 },
                new Achievement { Id = "all_workshops_8", Category = AchievementCategory.Workshops, TargetValue = 8, MoneyReward = 100000, XpReward = 1000, GoldenScrewReward = 20 },
                new Achievement { Id = "events_survived_10", Category = AchievementCategory.Workshops, TargetValue = 10, MoneyReward = 5000, XpReward = 150 },
                new Achievement { Id = "money_1k", Category = AchievementCategory.Money, TargetValue = 1000, MoneyReward = 100, XpReward = 10 },
                new Achievement { Id = "money_10k", Category = AchievementCategory.Money, TargetValue = 10000, MoneyReward = 500, XpReward = 25 },
                new Achievement { Id = "money_100k", Category = AchievementCategory.Money, TargetValue = 100000, MoneyReward = 2500, XpReward = 100 },
                new Achievement { Id = "money_1m", Category = AchievementCategory.Money, TargetValue = 1000000, MoneyReward = 10000, XpReward = 250, GoldenScrewReward = 15 },
                new Achievement { Id = "money_10m", Category = AchievementCategory.Money, TargetValue = 10000000, MoneyReward = 25000, XpReward = 400 },
                new Achievement { Id = "money_100m", Category = AchievementCategory.Money, TargetValue = 100000000, MoneyReward = 50000, XpReward = 600, GoldenScrewReward = 30 },
                new Achievement { Id = "money_1b", Category = AchievementCategory.Money, TargetValue = 1_000_000_000, MoneyReward = 100000, XpReward = 1000 },
                new Achievement { Id = "money_10b", Category = AchievementCategory.Money, TargetValue = 10_000_000_000, MoneyReward = 1_000_000, XpReward = 2500, GoldenScrewReward = 100 },
                new Achievement { Id = "play_1h", Category = AchievementCategory.Time, TargetValue = 3600, MoneyReward = 250, XpReward = 20 },
                new Achievement { Id = "play_10h", Category = AchievementCategory.Time, TargetValue = 36000, MoneyReward = 2500, XpReward = 150 },
                new Achievement { Id = "daily_7", Category = AchievementCategory.Time, TargetValue = 7, MoneyReward = 1000, XpReward = 50 },
                new Achievement { Id = "level_10", Category = AchievementCategory.Special, TargetValue = 10, MoneyReward = 2000, XpReward = 0 },
                new Achievement { Id = "level_25", Category = AchievementCategory.Special, TargetValue = 25, MoneyReward = 10000, XpReward = 0, GoldenScrewReward = 5 },
                new Achievement { Id = "level_50", Category = AchievementCategory.Special, TargetValue = 50, MoneyReward = 25000, XpReward = 0, GoldenScrewReward = 10 },
                new Achievement { Id = "level_100", Category = AchievementCategory.Special, TargetValue = 100, MoneyReward = 100_000, XpReward = 0, GoldenScrewReward = 30 },
                new Achievement { Id = "level_250", Category = AchievementCategory.Special, TargetValue = 250, MoneyReward = 500_000, XpReward = 0, GoldenScrewReward = 50 },
                new Achievement { Id = "level_500", Category = AchievementCategory.Special, TargetValue = 500, MoneyReward = 5_000_000, XpReward = 0, GoldenScrewReward = 100 },
                new Achievement { Id = "level_1000", Category = AchievementCategory.Special, TargetValue = 1000, MoneyReward = 50_000_000, XpReward = 0, GoldenScrewReward = 250 },
                new Achievement { Id = "prestige_1", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 5000, XpReward = 250 },
                new Achievement { Id = "worker_a_tier", Category = AchievementCategory.Workers, TargetValue = 1, MoneyReward = 10000, XpReward = 200 },
                new Achievement { Id = "workers_max_level", Category = AchievementCategory.Workers, TargetValue = 10, MoneyReward = 25000, XpReward = 400 },
                new Achievement { Id = "worker_loyal", Category = AchievementCategory.Workers, TargetValue = 100, MoneyReward = 15000, XpReward = 300 },
                new Achievement { Id = "worker_specialist", Category = AchievementCategory.Workers, TargetValue = 1, MoneyReward = 500, XpReward = 15 },
                new Achievement { Id = "workers_total_50", Category = AchievementCategory.Workers, TargetValue = 50, MoneyReward = 20000, XpReward = 350 },
                new Achievement { Id = "worker_s_tier", Category = AchievementCategory.Workers, TargetValue = 1, MoneyReward = 50000, XpReward = 500 },
                new Achievement { Id = "worker_ss_tier", Category = AchievementCategory.Workers, TargetValue = 1, MoneyReward = 200_000, XpReward = 1000, GoldenScrewReward = 30 },
                new Achievement { Id = "worker_sss_tier", Category = AchievementCategory.Workers, TargetValue = 1, MoneyReward = 1_000_000, XpReward = 2500, GoldenScrewReward = 50 },
                new Achievement { Id = "worker_legendary", Category = AchievementCategory.Workers, TargetValue = 1, MoneyReward = 10_000_000, XpReward = 5000, GoldenScrewReward = 100 },
                new Achievement { Id = "building_first", Category = AchievementCategory.Buildings, TargetValue = 1, MoneyReward = 2000, XpReward = 25 },
                new Achievement { Id = "building_all", Category = AchievementCategory.Buildings, TargetValue = 7, MoneyReward = 50000, XpReward = 500 },
                new Achievement { Id = "building_max", Category = AchievementCategory.Buildings, TargetValue = 5, MoneyReward = 20000, XpReward = 250 },
                new Achievement { Id = "canteen_built", Category = AchievementCategory.Buildings, TargetValue = 1, MoneyReward = 5000, XpReward = 50 },
                new Achievement { Id = "training_center", Category = AchievementCategory.Buildings, TargetValue = 1, MoneyReward = 5000, XpReward = 50 },
                new Achievement { Id = "research_first", Category = AchievementCategory.Research, TargetValue = 1, MoneyReward = 2000, XpReward = 25 },
                new Achievement { Id = "research_branch", Category = AchievementCategory.Research, TargetValue = 15, MoneyReward = 100000, XpReward = 1000 },
                new Achievement { Id = "research_all", Category = AchievementCategory.Research, TargetValue = 45, MoneyReward = 500000, XpReward = 3000 },
                new Achievement { Id = "research_tools5", Category = AchievementCategory.Research, TargetValue = 5, MoneyReward = 10000, XpReward = 100 },
                new Achievement { Id = "research_mgmt5", Category = AchievementCategory.Research, TargetValue = 5, MoneyReward = 10000, XpReward = 100 },
                new Achievement { Id = "reputation_70", Category = AchievementCategory.Reputation, TargetValue = 70, MoneyReward = 10000, XpReward = 150 },
                new Achievement { Id = "reputation_90", Category = AchievementCategory.Reputation, TargetValue = 90, MoneyReward = 25000, XpReward = 300 },
                new Achievement { Id = "reputation_100", Category = AchievementCategory.Reputation, TargetValue = 100, MoneyReward = 100000, XpReward = 750 },
                new Achievement { Id = "regular_10", Category = AchievementCategory.Reputation, TargetValue = 10, MoneyReward = 15000, XpReward = 250 },
                new Achievement { Id = "prestige_bronze", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 10000, XpReward = 250, GoldenScrewReward = 20 },
                new Achievement { Id = "prestige_silver", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 50000, XpReward = 750, GoldenScrewReward = 50 },
                new Achievement { Id = "prestige_gold", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 200000, XpReward = 1500, GoldenScrewReward = 100 },
                new Achievement { Id = "prestige_points_100", Category = AchievementCategory.Prestige, TargetValue = 100, MoneyReward = 50000, XpReward = 500 },
                new Achievement { Id = "prestige_total_5", Category = AchievementCategory.Prestige, TargetValue = 5, MoneyReward = 25_000, XpReward = 500, GoldenScrewReward = 25 },
                new Achievement { Id = "prestige_total_10", Category = AchievementCategory.Prestige, TargetValue = 10, MoneyReward = 100_000, XpReward = 1500, GoldenScrewReward = 50 },
                new Achievement { Id = "prestige_total_25", Category = AchievementCategory.Prestige, TargetValue = 25, MoneyReward = 500_000, XpReward = 3000, GoldenScrewReward = 100 },
                new Achievement { Id = "prestige_total_50", Category = AchievementCategory.Prestige, TargetValue = 50, MoneyReward = 2_000_000, XpReward = 7500, GoldenScrewReward = 250 },
                new Achievement { Id = "prestige_points_1000", Category = AchievementCategory.Prestige, TargetValue = 1000, MoneyReward = 1_000_000, XpReward = 5000, GoldenScrewReward = 150 },
                new Achievement { Id = "prestige_platin", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 500_000, XpReward = 3000, GoldenScrewReward = 150 },
                new Achievement { Id = "prestige_diamant", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 2_000_000, XpReward = 5000, GoldenScrewReward = 250 },
                new Achievement { Id = "prestige_meister", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 10_000_000, XpReward = 10000, GoldenScrewReward = 500 },
                new Achievement { Id = "prestige_legende", Category = AchievementCategory.Prestige, TargetValue = 1, MoneyReward = 50_000_000, XpReward = 25000, GoldenScrewReward = 1000 },
                new Achievement { Id = "perfect_100", Category = AchievementCategory.MiniGames, TargetValue = 100, MoneyReward = 50_000, XpReward = 1000, GoldenScrewReward = 30 },
                new Achievement { Id = "games_500", Category = AchievementCategory.MiniGames, TargetValue = 500, MoneyReward = 100_000, XpReward = 2000, GoldenScrewReward = 50 },
                new Achievement { Id = "all_minigames_perfect", Category = AchievementCategory.MiniGames, TargetValue = 8, MoneyReward = 200_000, XpReward = 3000, GoldenScrewReward = 75 },
                new Achievement { Id = "all_ws_level100", Category = AchievementCategory.Workshops, TargetValue = 8, MoneyReward = 5_000_000, XpReward = 5000, GoldenScrewReward = 100 },
                new Achievement { Id = "guild_founder", Category = AchievementCategory.Guilds, TargetValue = 1, MoneyReward = 10_000, XpReward = 250, GoldenScrewReward = 20 },
                new Achievement { Id = "guild_member", Category = AchievementCategory.Guilds, TargetValue = 1, MoneyReward = 5_000, XpReward = 100 },
                new Achievement { Id = "guild_weekly_goal", Category = AchievementCategory.Guilds, TargetValue = 1, MoneyReward = 25_000, XpReward = 500, GoldenScrewReward = 25 },
                new Achievement { Id = "guild_level_10", Category = AchievementCategory.Guilds, TargetValue = 10, MoneyReward = 100_000, XpReward = 1500, GoldenScrewReward = 50 },
                new Achievement { Id = "workers_trained_50", Category = AchievementCategory.Workers, TargetValue = 50, MoneyReward = 50_000, XpReward = 750, GoldenScrewReward = 25 },
                new Achievement { Id = "crafting_100", Category = AchievementCategory.Crafting, TargetValue = 100, MoneyReward = 100_000, XpReward = 1500, GoldenScrewReward = 30 },
                new Achievement { Id = "all_recipes", Category = AchievementCategory.Crafting, TargetValue = 13, MoneyReward = 200_000, XpReward = 2500, GoldenScrewReward = 50 },
                new Achievement { Id = "tournament_gold", Category = AchievementCategory.Tournaments, TargetValue = 1, MoneyReward = 25_000, XpReward = 500, GoldenScrewReward = 20 },
                new Achievement { Id = "tournaments_10", Category = AchievementCategory.Tournaments, TargetValue = 10, MoneyReward = 100_000, XpReward = 2000, GoldenScrewReward = 50 },
                new Achievement { Id = "all_mastertools", Category = AchievementCategory.Collection, TargetValue = 12, MoneyReward = 500_000, XpReward = 3000, GoldenScrewReward = 75 },
                new Achievement { Id = "equipment_all_rarities", Category = AchievementCategory.Collection, TargetValue = 4, MoneyReward = 100_000, XpReward = 1500, GoldenScrewReward = 30 },
                new Achievement { Id = "asc_first", Category = AchievementCategory.Ascension, TargetValue = 1, MoneyReward = 500_000, XpReward = 5000, GoldenScrewReward = 100 },
                new Achievement { Id = "asc_5", Category = AchievementCategory.Ascension, TargetValue = 5, MoneyReward = 5_000_000, XpReward = 12500, GoldenScrewReward = 250 },
                new Achievement { Id = "asc_10", Category = AchievementCategory.Ascension, TargetValue = 10, MoneyReward = 50_000_000, XpReward = 25000, GoldenScrewReward = 500 },
                new Achievement { Id = "asc_perk_first", Category = AchievementCategory.Ascension, TargetValue = 1, MoneyReward = 100_000, XpReward = 2500, GoldenScrewReward = 50 },
                new Achievement { Id = "asc_perks_max", Category = AchievementCategory.Ascension, TargetValue = 6, MoneyReward = 100_000_000, XpReward = 50000, GoldenScrewReward = 1000 },
                new Achievement { Id = "rebirth_first", Category = AchievementCategory.Rebirth, TargetValue = 1, MoneyReward = 1_000_000, XpReward = 5000, GoldenScrewReward = 100 },
                new Achievement { Id = "rebirth_stars_10", Category = AchievementCategory.Rebirth, TargetValue = 10, MoneyReward = 10_000_000, XpReward = 15000, GoldenScrewReward = 300 },
                new Achievement { Id = "rebirth_ws_5stars", Category = AchievementCategory.Rebirth, TargetValue = 5, MoneyReward = 25_000_000, XpReward = 20000, GoldenScrewReward = 500 },
                new Achievement { Id = "rebirth_all_ws", Category = AchievementCategory.Rebirth, TargetValue = 8, MoneyReward = 50_000_000, XpReward = 25000, GoldenScrewReward = 750 },
                new Achievement { Id = "all_ws_level1000", Category = AchievementCategory.Workshops, TargetValue = 8, MoneyReward = 100_000_000, XpReward = 50000, GoldenScrewReward = 1000 },
                new Achievement { Id = "auto_craft_first", Category = AchievementCategory.Crafting, TargetValue = 1, MoneyReward = 1_000, XpReward = 500, GoldenScrewReward = 5 },
                new Achievement { Id = "auto_craft_100", Category = AchievementCategory.Crafting, TargetValue = 100, MoneyReward = 25_000, XpReward = 2500, GoldenScrewReward = 25 },
                new Achievement { Id = "auto_craft_1000", Category = AchievementCategory.Crafting, TargetValue = 1000, MoneyReward = 250_000, XpReward = 10000, GoldenScrewReward = 100 },
                new Achievement { Id = "material_order_10", Category = AchievementCategory.Orders, TargetValue = 10, MoneyReward = 50_000, XpReward = 5000, GoldenScrewReward = 50 },
                new Achievement { Id = "craft_tier3_first", Category = AchievementCategory.Crafting, TargetValue = 1, MoneyReward = 100_000, XpReward = 5000, GoldenScrewReward = 50 },

            };
        }
    }
}
