//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeasure.Shared.Resources.Strings {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMeasure.Shared.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // Navigation / Tabs
        public static string TabSurvey => ResourceManager.GetString("TabSurvey", resourceCulture) ?? "";
        public static string TabTerrain => ResourceManager.GetString("TabTerrain", resourceCulture) ?? "";
        public static string TabGarden => ResourceManager.GetString("TabGarden", resourceCulture) ?? "";
        public static string TabMap => ResourceManager.GetString("TabMap", resourceCulture) ?? "";
        public static string TabProjects => ResourceManager.GetString("TabProjects", resourceCulture) ?? "";
        public static string TabSettings => ResourceManager.GetString("TabSettings", resourceCulture) ?? "";

        // Survey: Position
        public static string Position => ResourceManager.GetString("Position", resourceCulture) ?? "";
        public static string Latitude => ResourceManager.GetString("Latitude", resourceCulture) ?? "";
        public static string Longitude => ResourceManager.GetString("Longitude", resourceCulture) ?? "";
        public static string Altitude => ResourceManager.GetString("Altitude", resourceCulture) ?? "";
        public static string HAccuracy => ResourceManager.GetString("HAccuracy", resourceCulture) ?? "";
        public static string VAccuracy => ResourceManager.GetString("VAccuracy", resourceCulture) ?? "";
        public static string Tilt => ResourceManager.GetString("Tilt", resourceCulture) ?? "";

        // Survey: Labels + Actions
        public static string PointLabel => ResourceManager.GetString("PointLabel", resourceCulture) ?? "";
        public static string CustomLabelWatermark => ResourceManager.GetString("CustomLabelWatermark", resourceCulture) ?? "";
        public static string SetPoint => ResourceManager.GetString("SetPoint", resourceCulture) ?? "";
        public static string ArCamera => ResourceManager.GetString("ArCamera", resourceCulture) ?? "";
        public static string Distance => ResourceManager.GetString("Distance", resourceCulture) ?? "";
        public static string MeasurePoints => ResourceManager.GetString("MeasurePoints", resourceCulture) ?? "";
        public static string DeleteAll => ResourceManager.GetString("DeleteAll", resourceCulture) ?? "";

        // Survey: Quick Labels
        public static string QuickLabelCorner => ResourceManager.GetString("QuickLabelCorner", resourceCulture) ?? "";
        public static string QuickLabelBorder => ResourceManager.GetString("QuickLabelBorder", resourceCulture) ?? "";
        public static string QuickLabelTree => ResourceManager.GetString("QuickLabelTree", resourceCulture) ?? "";
        public static string QuickLabelPost => ResourceManager.GetString("QuickLabelPost", resourceCulture) ?? "";
        public static string QuickLabelPath => ResourceManager.GetString("QuickLabelPath", resourceCulture) ?? "";

        // Terrain
        public static string TerrainModel => ResourceManager.GetString("TerrainModel", resourceCulture) ?? "";
        public static string Points => ResourceManager.GetString("Points", resourceCulture) ?? "";
        public static string Area => ResourceManager.GetString("Area", resourceCulture) ?? "";
        public static string HeightRange => ResourceManager.GetString("HeightRange", resourceCulture) ?? "";
        public static string Elevation => ResourceManager.GetString("Elevation", resourceCulture) ?? "";
        public static string Wireframe => ResourceManager.GetString("Wireframe", resourceCulture) ?? "";
        public static string Contours => ResourceManager.GetString("Contours", resourceCulture) ?? "";
        public static string Reset => ResourceManager.GetString("Reset", resourceCulture) ?? "";
        public static string Flat => ResourceManager.GetString("Flat", resourceCulture) ?? "";

        // Garden
        public static string GardenPlan => ResourceManager.GetString("GardenPlan", resourceCulture) ?? "";
        public static string Path => ResourceManager.GetString("Path", resourceCulture) ?? "";
        public static string Bed => ResourceManager.GetString("Bed", resourceCulture) ?? "";
        public static string Lawn => ResourceManager.GetString("Lawn", resourceCulture) ?? "";
        public static string GardenWall => ResourceManager.GetString("GardenWall", resourceCulture) ?? "";
        public static string Fence => ResourceManager.GetString("Fence", resourceCulture) ?? "";
        public static string Terrace => ResourceManager.GetString("Terrace", resourceCulture) ?? "";
        public static string Building => ResourceManager.GetString("Building", resourceCulture) ?? "";
        public static string Water => ResourceManager.GetString("Water", resourceCulture) ?? "";
        public static string GardenBorder => ResourceManager.GetString("GardenBorder", resourceCulture) ?? "";
        public static string Materials => ResourceManager.GetString("Materials", resourceCulture) ?? "";
        public static string SafetyMarginNote => ResourceManager.GetString("SafetyMarginNote", resourceCulture) ?? "";
        public static string Undo => ResourceManager.GetString("Undo", resourceCulture) ?? "";
        public static string Redo => ResourceManager.GetString("Redo", resourceCulture) ?? "";

        // Map
        public static string MapView => ResourceManager.GetString("MapView", resourceCulture) ?? "";
        public static string Perimeter => ResourceManager.GetString("Perimeter", resourceCulture) ?? "";
        public static string PointCount => ResourceManager.GetString("PointCount", resourceCulture) ?? "";

        // Projects
        public static string Projects => ResourceManager.GetString("Projects", resourceCulture) ?? "";
        public static string NewProject => ResourceManager.GetString("NewProject", resourceCulture) ?? "";
        public static string NewProjectWatermark => ResourceManager.GetString("NewProjectWatermark", resourceCulture) ?? "";
        public static string ProjectName => ResourceManager.GetString("ProjectName", resourceCulture) ?? "";
        public static string Create => ResourceManager.GetString("Create", resourceCulture) ?? "";
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture) ?? "";
        public static string Open => ResourceManager.GetString("Open", resourceCulture) ?? "";
        public static string Duplicate => ResourceManager.GetString("Duplicate", resourceCulture) ?? "";
        public static string Copy => ResourceManager.GetString("Copy", resourceCulture) ?? "";
        public static string Export => ResourceManager.GetString("Export", resourceCulture) ?? "";
        public static string ExportCsv => ResourceManager.GetString("ExportCsv", resourceCulture) ?? "";
        public static string ExportGeoJson => ResourceManager.GetString("ExportGeoJson", resourceCulture) ?? "";
        public static string ExportObj => ResourceManager.GetString("ExportObj", resourceCulture) ?? "";
        public static string ExportPdf => ResourceManager.GetString("ExportPdf", resourceCulture) ?? "";

        // Connect

        // Settings
        public static string Settings => ResourceManager.GetString("Settings", resourceCulture) ?? "";
        public static string Units => ResourceManager.GetString("Units", resourceCulture) ?? "";
        public static string Metric => ResourceManager.GetString("Metric", resourceCulture) ?? "";
        public static string Imperial => ResourceManager.GetString("Imperial", resourceCulture) ?? "";
        public static string AppVersion => ResourceManager.GetString("AppVersion", resourceCulture) ?? "";
        public static string AppDescription => ResourceManager.GetString("AppDescription", resourceCulture) ?? "";

        // Common
        public static string OK => ResourceManager.GetString("OK", resourceCulture) ?? "";
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? "";
        public static string Save => ResourceManager.GetString("Save", resourceCulture) ?? "";
        public static string Back => ResourceManager.GetString("Back", resourceCulture) ?? "";
        public static string Error => ResourceManager.GetString("Error", resourceCulture) ?? "";
        public static string Loading => ResourceManager.GetString("Loading", resourceCulture) ?? "";
        public static string NoData => ResourceManager.GetString("NoData", resourceCulture) ?? "";
        public static string Confirm => ResourceManager.GetString("Confirm", resourceCulture) ?? "";

        // AR
        public static string ArCapture => ResourceManager.GetString("ArCapture", resourceCulture) ?? "";
        public static string ArNotAvailable => ResourceManager.GetString("ArNotAvailable", resourceCulture) ?? "";
        public static string ArActive => ResourceManager.GetString("ArActive", resourceCulture) ?? "";
        public static string ArPointsCaptured => ResourceManager.GetString("ArPointsCaptured", resourceCulture) ?? "";
        public static string ArCancelled => ResourceManager.GetString("ArCancelled", resourceCulture) ?? "";
        public static string PointMode => ResourceManager.GetString("PointMode", resourceCulture) ?? "";
        public static string LineMode => ResourceManager.GetString("LineMode", resourceCulture) ?? "";
        public static string CloseContour => ResourceManager.GetString("CloseContour", resourceCulture) ?? "";
        public static string Finish => ResourceManager.GetString("Finish", resourceCulture) ?? "";

        // Fix Status

        // Back Button
        public static string PressBackAgainToExit => ResourceManager.GetString("PressBackAgainToExit", resourceCulture) ?? "";

        // AR-Capture Stats-Panel + Tracking-Reasons (Plan-Kap. 4.11)
        public static string ArStatPoints => ResourceManager.GetString("ArStatPoints", resourceCulture) ?? "";
        public static string ArStatArea => ResourceManager.GetString("ArStatArea", resourceCulture) ?? "";
        public static string ArStatPlanes => ResourceManager.GetString("ArStatPlanes", resourceCulture) ?? "";
        public static string ArStatLength => ResourceManager.GetString("ArStatLength", resourceCulture) ?? "";
        public static string ArStatHeightDelta => ResourceManager.GetString("ArStatHeightDelta", resourceCulture) ?? "";
        public static string ArStatAnchors => ResourceManager.GetString("ArStatAnchors", resourceCulture) ?? "";
        public static string ArStatTime => ResourceManager.GetString("ArStatTime", resourceCulture) ?? "";
        public static string ArReticleHoldStill => ResourceManager.GetString("ArReticleHoldStill", resourceCulture) ?? "";
        public static string ArBadgeReady => ResourceManager.GetString("ArBadgeReady", resourceCulture) ?? "";
        public static string ArTrackingLost => ResourceManager.GetString("ArTrackingLost", resourceCulture) ?? "";
        public static string ArTrackingInsufficientLight => ResourceManager.GetString("ArTrackingInsufficientLight", resourceCulture) ?? "";
        public static string ArTrackingInsufficientFeatures => ResourceManager.GetString("ArTrackingInsufficientFeatures", resourceCulture) ?? "";
        public static string ArTrackingExcessiveMotion => ResourceManager.GetString("ArTrackingExcessiveMotion", resourceCulture) ?? "";
        public static string ArTrackingCameraUnavailable => ResourceManager.GetString("ArTrackingCameraUnavailable", resourceCulture) ?? "";
        public static string ArTrackingBadState => ResourceManager.GetString("ArTrackingBadState", resourceCulture) ?? "";
    }
}
