//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebornSaga.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RebornSaga.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // App
        internal static string AppName {
            get { return ResourceManager.GetString("AppName", resourceCulture); }
        }

        // Title Scene
        internal static string NewGame {
            get { return ResourceManager.GetString("NewGame", resourceCulture); }
        }

        internal static string Continue {
            get { return ResourceManager.GetString("Continue", resourceCulture); }
        }

        internal static string Settings {
            get { return ResourceManager.GetString("Settings", resourceCulture); }
        }

        // Save Slot Scene
        internal static string ChooseSaveSlot {
            get { return ResourceManager.GetString("ChooseSaveSlot", resourceCulture); }
        }

        internal static string Back {
            get { return ResourceManager.GetString("Back", resourceCulture); }
        }

        internal static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }

        internal static string Delete {
            get { return ResourceManager.GetString("Delete", resourceCulture); }
        }

        // Class Select Scene
        internal static string ClassSwordmaster {
            get { return ResourceManager.GetString("ClassSwordmaster", resourceCulture); }
        }

        internal static string ClassArcanist {
            get { return ResourceManager.GetString("ClassArcanist", resourceCulture); }
        }

        internal static string ClassShadowblade {
            get { return ResourceManager.GetString("ClassShadowblade", resourceCulture); }
        }

        internal static string Confirm {
            get { return ResourceManager.GetString("Confirm", resourceCulture); }
        }

        // Dialogue Scene
        internal static string Log {
            get { return ResourceManager.GetString("Log", resourceCulture); }
        }

        internal static string Auto {
            get { return ResourceManager.GetString("Auto", resourceCulture); }
        }

        internal static string AutoOn {
            get { return ResourceManager.GetString("AutoOn", resourceCulture); }
        }

        internal static string Skip {
            get { return ResourceManager.GetString("Skip", resourceCulture); }
        }

        // Battle Scene
        internal static string Attack {
            get { return ResourceManager.GetString("Attack", resourceCulture); }
        }

        internal static string Dodge {
            get { return ResourceManager.GetString("Dodge", resourceCulture); }
        }

        internal static string Skill {
            get { return ResourceManager.GetString("Skill", resourceCulture); }
        }

        internal static string Item {
            get { return ResourceManager.GetString("Item", resourceCulture); }
        }

        internal static string Victory {
            get { return ResourceManager.GetString("Victory", resourceCulture); }
        }

        internal static string Defeat {
            get { return ResourceManager.GetString("Defeat", resourceCulture); }
        }

        internal static string TapToContinue {
            get { return ResourceManager.GetString("TapToContinue", resourceCulture); }
        }

        internal static string ChooseSkill {
            get { return ResourceManager.GetString("ChooseSkill", resourceCulture); }
        }

        internal static string ChooseItem {
            get { return ResourceManager.GetString("ChooseItem", resourceCulture); }
        }

        internal static string NoSkillsAvailable {
            get { return ResourceManager.GetString("NoSkillsAvailable", resourceCulture); }
        }

        internal static string NoItemsAvailable {
            get { return ResourceManager.GetString("NoItemsAvailable", resourceCulture); }
        }

        internal static string BossPhase {
            get { return ResourceManager.GetString("BossPhase", resourceCulture); }
        }

        internal static string Combo {
            get { return ResourceManager.GetString("Combo", resourceCulture); }
        }

        internal static string Boss {
            get { return ResourceManager.GetString("Boss", resourceCulture); }
        }

        // Overworld Scene
        internal static string Menu {
            get { return ResourceManager.GetString("Menu", resourceCulture); }
        }

        // Inventory Scene
        internal static string Inventory {
            get { return ResourceManager.GetString("Inventory", resourceCulture); }
        }

        internal static string TabAll {
            get { return ResourceManager.GetString("TabAll", resourceCulture); }
        }

        internal static string TabWeapons {
            get { return ResourceManager.GetString("TabWeapons", resourceCulture); }
        }

        internal static string TabArmor {
            get { return ResourceManager.GetString("TabArmor", resourceCulture); }
        }

        internal static string TabAccessory {
            get { return ResourceManager.GetString("TabAccessory", resourceCulture); }
        }

        internal static string TabConsumable {
            get { return ResourceManager.GetString("TabConsumable", resourceCulture); }
        }

        internal static string TabKeyItems {
            get { return ResourceManager.GetString("TabKeyItems", resourceCulture); }
        }

        internal static string TypeWeapon {
            get { return ResourceManager.GetString("TypeWeapon", resourceCulture); }
        }

        internal static string TypeArmor {
            get { return ResourceManager.GetString("TypeArmor", resourceCulture); }
        }

        internal static string TypeAccessory {
            get { return ResourceManager.GetString("TypeAccessory", resourceCulture); }
        }

        internal static string TypeConsumable {
            get { return ResourceManager.GetString("TypeConsumable", resourceCulture); }
        }

        internal static string TypeKeyItem {
            get { return ResourceManager.GetString("TypeKeyItem", resourceCulture); }
        }

        internal static string Equip {
            get { return ResourceManager.GetString("Equip", resourceCulture); }
        }

        internal static string Unequip {
            get { return ResourceManager.GetString("Unequip", resourceCulture); }
        }

        internal static string Use {
            get { return ResourceManager.GetString("Use", resourceCulture); }
        }

        // Shop Scene
        internal static string Merchant {
            get { return ResourceManager.GetString("Merchant", resourceCulture); }
        }

        internal static string Buy {
            get { return ResourceManager.GetString("Buy", resourceCulture); }
        }

        internal static string Sell {
            get { return ResourceManager.GetString("Sell", resourceCulture); }
        }

        internal static string NothingToSell {
            get { return ResourceManager.GetString("NothingToSell", resourceCulture); }
        }

        internal static string NoWares {
            get { return ResourceManager.GetString("NoWares", resourceCulture); }
        }

        // Status Scene
        internal static string Status {
            get { return ResourceManager.GetString("Status", resourceCulture); }
        }

        internal static string Skills {
            get { return ResourceManager.GetString("Skills", resourceCulture); }
        }

        internal static string Equipment {
            get { return ResourceManager.GetString("Equipment", resourceCulture); }
        }

        internal static string Free {
            get { return ResourceManager.GetString("Free", resourceCulture); }
        }

        internal static string Buff {
            get { return ResourceManager.GetString("Buff", resourceCulture); }
        }

        internal static string ClassMage {
            get { return ResourceManager.GetString("ClassMage", resourceCulture); }
        }

        internal static string ClassAssassin {
            get { return ResourceManager.GetString("ClassAssassin", resourceCulture); }
        }

        // Settings Scene
        internal static string Audio {
            get { return ResourceManager.GetString("Audio", resourceCulture); }
        }

        internal static string SoundEffects {
            get { return ResourceManager.GetString("SoundEffects", resourceCulture); }
        }

        internal static string Music {
            get { return ResourceManager.GetString("Music", resourceCulture); }
        }

        internal static string Vibration {
            get { return ResourceManager.GetString("Vibration", resourceCulture); }
        }

        internal static string Text {
            get { return ResourceManager.GetString("Text", resourceCulture); }
        }

        internal static string Speed {
            get { return ResourceManager.GetString("Speed", resourceCulture); }
        }

        internal static string SpeedSlow {
            get { return ResourceManager.GetString("SpeedSlow", resourceCulture); }
        }

        internal static string SpeedNormal {
            get { return ResourceManager.GetString("SpeedNormal", resourceCulture); }
        }

        internal static string SpeedFast {
            get { return ResourceManager.GetString("SpeedFast", resourceCulture); }
        }

        internal static string SpeedInstant {
            get { return ResourceManager.GetString("SpeedInstant", resourceCulture); }
        }

        internal static string SfxVolume {
            get { return ResourceManager.GetString("SfxVolume", resourceCulture); }
        }

        internal static string MusicVolume {
            get { return ResourceManager.GetString("MusicVolume", resourceCulture); }
        }

        // Pause Overlay
        internal static string Pause {
            get { return ResourceManager.GetString("Pause", resourceCulture); }
        }

        internal static string Resume {
            get { return ResourceManager.GetString("Resume", resourceCulture); }
        }

        internal static string Save {
            get { return ResourceManager.GetString("Save", resourceCulture); }
        }

        internal static string Codex {
            get { return ResourceManager.GetString("Codex", resourceCulture); }
        }

        internal static string MainMenu {
            get { return ResourceManager.GetString("MainMenu", resourceCulture); }
        }

        internal static string Saving {
            get { return ResourceManager.GetString("Saving", resourceCulture); }
        }

        // Overlays
        internal static string Close {
            get { return ResourceManager.GetString("Close", resourceCulture); }
        }

        internal static string LoadSave {
            get { return ResourceManager.GetString("LoadSave", resourceCulture); }
        }

        internal static string UnlockChapter {
            get { return ResourceManager.GetString("UnlockChapter", resourceCulture); }
        }

        internal static string Unlock {
            get { return ResourceManager.GetString("Unlock", resourceCulture); }
        }

        // Level Up Overlay
        internal static string LevelUp {
            get { return ResourceManager.GetString("LevelUp", resourceCulture); }
        }

        internal static string DistributePoints {
            get { return ResourceManager.GetString("DistributePoints", resourceCulture); }
        }

        internal static string AllPointsDistributed {
            get { return ResourceManager.GetString("AllPointsDistributed", resourceCulture); }
        }

        // Game Over Overlay
        internal static string YourJourneyEnds {
            get { return ResourceManager.GetString("YourJourneyEnds", resourceCulture); }
        }

        internal static string ReviveAd {
            get { return ResourceManager.GetString("ReviveAd", resourceCulture); }
        }

        internal static string LoadSaveGame {
            get { return ResourceManager.GetString("LoadSaveGame", resourceCulture); }
        }

        // Fate Changed Overlay
        internal static string FateChanged {
            get { return ResourceManager.GetString("FateChanged", resourceCulture); }
        }

        // Tutorial Overlay
        internal static string TapToContinueTutorial {
            get { return ResourceManager.GetString("TapToContinueTutorial", resourceCulture); }
        }

        // Backlog Overlay
        internal static string DialogBacklog {
            get { return ResourceManager.GetString("DialogBacklog", resourceCulture); }
        }

        // Chapter Unlock Overlay
        internal static string Cost {
            get { return ResourceManager.GetString("Cost", resourceCulture); }
        }

        internal static string YourGold {
            get { return ResourceManager.GetString("YourGold", resourceCulture); }
        }

        internal static string NoVideosToday {
            get { return ResourceManager.GetString("NoVideosToday", resourceCulture); }
        }

        internal static string WatchVideo {
            get { return ResourceManager.GetString("WatchVideo", resourceCulture); }
        }

        // Asset Download Scene
        internal static string CheckingAssets {
            get { return ResourceManager.GetString("CheckingAssets", resourceCulture); }
        }

        internal static string DownloadComplete {
            get { return ResourceManager.GetString("DownloadComplete", resourceCulture); }
        }

        internal static string DownloadFailed {
            get { return ResourceManager.GetString("DownloadFailed", resourceCulture); }
        }

        internal static string UseWifi {
            get { return ResourceManager.GetString("UseWifi", resourceCulture); }
        }

        internal static string RetryDownload {
            get { return ResourceManager.GetString("RetryDownload", resourceCulture); }
        }

        internal static string Ready {
            get { return ResourceManager.GetString("Ready", resourceCulture); }
        }

        // Asset Download (Format)
        internal static string DownloadingFiles {
            get { return ResourceManager.GetString("DownloadingFiles", resourceCulture); }
        }

        internal static string Downloading {
            get { return ResourceManager.GetString("Downloading", resourceCulture); }
        }

        // Navigation
        internal static string BackArrow {
            get { return ResourceManager.GetString("BackArrow", resourceCulture); }
        }

        // System
        internal static string PressBackAgainToExit {
            get { return ResourceManager.GetString("PressBackAgainToExit", resourceCulture); }
        }
    }
}
