//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTimePro.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkTimePro.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add entry ähnelt.
        /// </summary>
        internal static string AddEntry {
            get {
                return ResourceManager.GetString("AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto break ähnelt.
        /// </summary>
        internal static string AutoPause {
            get {
                return ResourceManager.GetString("AutoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto break added ähnelt.
        /// </summary>
        internal static string AutoPauseAdded {
            get {
                return ResourceManager.GetString("AutoPauseAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After hours ähnelt.
        /// </summary>
        internal static string AutoPauseAfterHours {
            get {
                return ResourceManager.GetString("AutoPauseAfterHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically add legally required break time ähnelt.
        /// </summary>
        internal static string AutoPauseDescription {
            get {
                return ResourceManager.GetString("AutoPauseDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto breaks are calculated automatically and cannot be deleted manually. ähnelt.
        /// </summary>
        internal static string AutoPauseCannotDelete {
            get {
                return ResourceManager.GetString("AutoPauseCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically added (legal requirement) ähnelt.
        /// </summary>
        internal static string AutoPauseLegal {
            get {
                return ResourceManager.GetString("AutoPauseLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break ähnelt.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break reminder ähnelt.
        /// </summary>
        internal static string BreakReminder {
            get {
                return ResourceManager.GetString("BreakReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy Premium ähnelt.
        /// </summary>
        internal static string BuyPremium {
            get {
                return ResourceManager.GetString("BuyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar ähnelt.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check-in ähnelt.
        /// </summary>
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check-out ähnelt.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close month ähnelt.
        /// </summary>
        internal static string CloseMonth {
            get {
                return ResourceManager.GetString("CloseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cumulative balance ähnelt.
        /// </summary>
        internal static string CumulativeBalance {
            get {
                return ResourceManager.GetString("CumulativeBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm delete ähnelt.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily target (hours) ähnelt.
        /// </summary>
        internal static string DailyTarget {
            get {
                return ResourceManager.GetString("DailyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day details ähnelt.
        /// </summary>
        internal static string DayDetails {
            get {
                return ResourceManager.GetString("DayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Business trip ähnelt.
        /// </summary>
        internal static string DayStatus_BusinessTrip {
            get {
                return ResourceManager.GetString("DayStatus_BusinessTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holiday ähnelt.
        /// </summary>
        internal static string DayStatus_Holiday {
            get {
                return ResourceManager.GetString("DayStatus_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home office ähnelt.
        /// </summary>
        internal static string DayStatus_HomeOffice {
            get {
                return ResourceManager.GetString("DayStatus_HomeOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sick ähnelt.
        /// </summary>
        internal static string DayStatus_Sick {
            get {
                return ResourceManager.GetString("DayStatus_Sick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation ähnelt.
        /// </summary>
        internal static string DayStatus_Vacation {
            get {
                return ResourceManager.GetString("DayStatus_Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekend ähnelt.
        /// </summary>
        internal static string DayStatus_Weekend {
            get {
                return ResourceManager.GetString("DayStatus_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work day ähnelt.
        /// </summary>
        internal static string DayStatus_WorkDay {
            get {
                return ResourceManager.GetString("DayStatus_WorkDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} days ähnelt.
        /// </summary>
        internal static string DaysFormat {
            get {
                return ResourceManager.GetString("DaysFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the entry at {0}? ähnelt.
        /// </summary>
        internal static string DeleteEntryConfirm {
            get {
                return ResourceManager.GetString("DeleteEntryConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the break from {0} to {1}? ähnelt.
        /// </summary>
        internal static string DeletePauseConfirm {
            get {
                return ResourceManager.GetString("DeletePauseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of day! ähnelt.
        /// </summary>
        internal static string EndOfDay {
            get {
                return ResourceManager.GetString("EndOfDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End break ähnelt.
        /// </summary>
        internal static string EndPause {
            get {
                return ResourceManager.GetString("EndPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of work ähnelt.
        /// </summary>
        internal static string EveningReminder {
            get {
                return ResourceManager.GetString("EveningReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free version with ads ähnelt.
        /// </summary>
        internal static string FreeVersion {
            get {
                return ResourceManager.GetString("FreeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fri ähnelt.
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friday ähnelt.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holidays ähnelt.
        /// </summary>
        internal static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal compliance check ähnelt.
        /// </summary>
        internal static string LegalCompliance {
            get {
                return ResourceManager.GetString("LegalCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show warnings for violations (max. 10h/day, min. 11h rest) ähnelt.
        /// </summary>
        internal static string LegalComplianceDescription {
            get {
                return ResourceManager.GetString("LegalComplianceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working Hours Act (ArbZG) ähnelt.
        /// </summary>
        internal static string LegalSourceArbZG {
            get {
                return ResourceManager.GetString("LegalSourceArbZG", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Public holidays (BMI) ähnelt.
        /// </summary>
        internal static string LegalSourceHolidays {
            get {
                return ResourceManager.GetString("LegalSourceHolidays", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal sources ähnelt.
        /// </summary>
        internal static string LegalSources {
            get {
                return ResourceManager.GetString("LegalSources", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break regulations description ähnelt.
        /// </summary>
        internal static string LegalSourcesDescription {
            get {
                return ResourceManager.GetString("LegalSourcesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legend ähnelt.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual break ähnelt.
        /// </summary>
        internal static string ManualPause {
            get {
                return ResourceManager.GetString("ManualPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mon ähnelt.
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monday ähnelt.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month balance ähnelt.
        /// </summary>
        internal static string MonthBalance {
            get {
                return ResourceManager.GetString("MonthBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month overview ähnelt.
        /// </summary>
        internal static string MonthOverview {
            get {
                return ResourceManager.GetString("MonthOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start of work ähnelt.
        /// </summary>
        internal static string MorningReminder {
            get {
                return ResourceManager.GetString("MorningReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No entries ähnelt.
        /// </summary>
        internal static string NoEntries {
            get {
                return ResourceManager.GetString("NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime ähnelt.
        /// </summary>
        internal static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime warning ähnelt.
        /// </summary>
        internal static string OvertimeWarning {
            get {
                return ResourceManager.GetString("OvertimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warn after hours/week ähnelt.
        /// </summary>
        internal static string OvertimeWarningHours {
            get {
                return ResourceManager.GetString("OvertimeWarningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break duration (minutes) ähnelt.
        /// </summary>
        internal static string PauseMinutes {
            get {
                return ResourceManager.GetString("PauseMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaks ähnelt.
        /// </summary>
        internal static string Pauses {
            get {
                return ResourceManager.GetString("Pauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium active ähnelt.
        /// </summary>
        internal static string PremiumActive {
            get {
                return ResourceManager.GetString("PremiumActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium status ähnelt.
        /// </summary>
        internal static string PremiumStatus {
            get {
                return ResourceManager.GetString("PremiumStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quarter ähnelt.
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Region ähnelt.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining ähnelt.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminders ähnelt.
        /// </summary>
        public static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore purchases ähnelt.
        /// </summary>
        internal static string RestorePurchases {
            get {
                return ResourceManager.GetString("RestorePurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sat ähnelt.
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saturday ähnelt.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not started ähnelt.
        /// </summary>
        internal static string Status_Idle {
            get {
                return ResourceManager.GetString("Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On break ähnelt.
        /// </summary>
        internal static string Status_OnBreak {
            get {
                return ResourceManager.GetString("Status_OnBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working ähnelt.
        /// </summary>
        internal static string Status_Working {
            get {
                return ResourceManager.GetString("Status_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sun ähnelt.
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sunday ähnelt.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target ähnelt.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design ähnelt.
        /// </summary>
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thu ähnelt.
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thursday ähnelt.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time entries ähnelt.
        /// </summary>
        internal static string TimeEntries {
            get {
                return ResourceManager.GetString("TimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today ähnelt.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trial: {0} days left ähnelt.
        /// </summary>
        internal static string TrialDaysLeft {
            get {
                return ResourceManager.GetString("TrialDaysLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 14 days free trial ähnelt.
        /// </summary>
        internal static string TrialOfferStart {
            get {
                return ResourceManager.GetString("TrialOfferStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You now have {0} days of Premium without ads. Enjoy! ähnelt.
        /// </summary>
        internal static string TrialStartedMessage {
            get {
                return ResourceManager.GetString("TrialStartedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Premium ähnelt.
        /// </summary>
        internal static string PurchaseOptionTitle {
            get {
                return ResourceManager.GetString("PurchaseOptionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly: €3.99/month ähnelt.
        /// </summary>
        internal static string PurchaseOptionMonthly {
            get {
                return ResourceManager.GetString("PurchaseOptionMonthly", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lifetime: €19.99 (one-time) ähnelt.
        /// </summary>
        internal static string PurchaseOptionLifetime {
            get {
                return ResourceManager.GetString("PurchaseOptionLifetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase successful! Thank you for your support. ähnelt.
        /// </summary>
        internal static string PurchaseSuccess {
            get {
                return ResourceManager.GetString("PurchaseSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscription active ähnelt.
        /// </summary>
        internal static string HasSubscription {
            get {
                return ResourceManager.GetString("HasSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lifetime Premium ähnelt.
        /// </summary>
        internal static string HasLifetime {
            get {
                return ResourceManager.GetString("HasLifetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tue ähnelt.
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tuesday ähnelt.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock month ähnelt.
        /// </summary>
        internal static string UnlockMonth {
            get {
                return ResourceManager.GetString("UnlockMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wed ähnelt.
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wednesday ähnelt.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly target ähnelt.
        /// </summary>
        internal static string WeeklyTarget {
            get {
                return ResourceManager.GetString("WeeklyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week progress ähnelt.
        /// </summary>
        internal static string WeekProgress {
            get {
                return ResourceManager.GetString("WeekProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work days ähnelt.
        /// </summary>
        internal static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work time ähnelt.
        /// </summary>
        internal static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work time ähnelt.
        /// </summary>
        internal static string WorkTimeSettings {
            get {
                return ResourceManager.GetString("WorkTimeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show day details ähnelt.
        /// </summary>
        internal static string ShowDayDetails {
            get {
                return ResourceManager.GetString("ShowDayDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days this week ähnelt.
        /// </summary>
        internal static string DaysThisWeek {
            get {
                return ResourceManager.GetString("DaysThisWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taken ähnelt.
        /// </summary>
        internal static string Taken {
            get {
                return ResourceManager.GetString("Taken", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No data ähnelt.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dem Hinweis "Benachrichtigungen deaktiviert" ähnelt.
        /// </summary>
        internal static string ReminderNotificationsOff {
            get {
                return ResourceManager.GetString("ReminderNotificationsOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dem Exact-Alarm-Permission-Hinweis ähnelt.
        /// </summary>
        internal static string ExactAlarmPermissionHint {
            get {
                return ResourceManager.GetString("ExactAlarmPermissionHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work time table ähnelt.
        /// </summary>
        internal static string WorkTimeTable {
            get {
                return ResourceManager.GetString("WorkTimeTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly work time ähnelt.
        /// </summary>
        internal static string WeeklyWorkTimeChart {
            get {
                return ResourceManager.GetString("WeeklyWorkTimeChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime trend ähnelt.
        /// </summary>
        internal static string OvertimeTrendChart {
            get {
                return ResourceManager.GetString("OvertimeTrendChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average by weekday ähnelt.
        /// </summary>
        internal static string WeekdayAverage {
            get {
                return ResourceManager.GetString("WeekdayAverage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project distribution ähnelt.
        /// </summary>
        internal static string ProjectDistribution {
            get {
                return ResourceManager.GetString("ProjectDistribution", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employer distribution ähnelt.
        /// </summary>
        internal static string EmployerDistribution {
            get {
                return ResourceManager.GetString("EmployerDistribution", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaks ähnelt.
        /// </summary>
        internal static string PauseStats {
            get {
                return ResourceManager.GetString("PauseStats", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation ähnelt.
        /// </summary>
        internal static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation days per year ähnelt.
        /// </summary>
        internal static string VacationDaysPerYear {
            get {
                return ResourceManager.GetString("VacationDaysPerYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default: 30 days ähnelt.
        /// </summary>
        internal static string VacationDefault {
            get {
                return ResourceManager.GetString("VacationDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individual hours per day ähnelt.
        /// </summary>
        internal static string IndividualHoursPerDay {
            get {
                return ResourceManager.GetString("IndividualHoursPerDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sick ähnelt.
        /// </summary>
        internal static string Sick {
            get {
                return ResourceManager.GetString("Sick", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holiday ähnelt.
        /// </summary>
        internal static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg/day ähnelt.
        /// </summary>
        internal static string AvgPerDay {
            get {
                return ResourceManager.GetString("AvgPerDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg/day ähnelt.
        /// </summary>
        internal static string AvgPerDayShort {
            get {
                return ResourceManager.GetString("AvgPerDayShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work days ähnelt.
        /// </summary>
        internal static string WorkedDaysCount {
            get {
                return ResourceManager.GetString("WorkedDaysCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset status ähnelt.
        /// </summary>
        internal static string ResetStatus {
            get {
                return ResourceManager.GetString("ResetStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} vacation days from {1} have been entered. ähnelt.
        /// </summary>
        internal static string VacationDaysEnteredFormat {
            get {
                return ResourceManager.GetString("VacationDaysEnteredFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die e.g. Project work ähnelt.
        /// </summary>
        internal static string NotePlaceholder {
            get {
                return ResourceManager.GetString("NotePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto breaks are calculated automatically. ähnelt.
        /// </summary>
        internal static string AutoBreakInfo {
            get {
                return ResourceManager.GetString("AutoBreakInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit break ähnelt.
        /// </summary>
        internal static string EditBreak {
            get {
                return ResourceManager.GetString("EditBreak", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime compensation ähnelt.
        /// </summary>
        internal static string OvertimeCompensation {
            get {
                return ResourceManager.GetString("OvertimeCompensation", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special leave ähnelt.
        /// </summary>
        internal static string SpecialLeave {
            get {
                return ResourceManager.GetString("SpecialLeave", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die planned ähnelt.
        /// </summary>
        internal static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note ähnelt.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected period contains no work days. ähnelt.
        /// </summary>
        internal static string NoWorkDaysInPeriod {
            get {
                return ResourceManager.GetString("NoWorkDaysInPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carry over days ähnelt.
        /// </summary>
        internal static string CarryOverDays {
            get {
                return ResourceManager.GetString("CarryOverDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} days from {1} have been carried over. ähnelt.
        /// </summary>
        internal static string DaysCarriedOver {
            get {
                return ResourceManager.GetString("DaysCarriedOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No remaining days from {0} to carry over. ähnelt.
        /// </summary>
        internal static string NoDaysToCarryOver {
            get {
                return ResourceManager.GetString("NoDaysToCarryOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illness ähnelt.
        /// </summary>
        internal static string Illness {
            get {
                return ResourceManager.GetString("Illness", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unpaid leave ähnelt.
        /// </summary>
        internal static string UnpaidLeave {
            get {
                return ResourceManager.GetString("UnpaidLeave", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string TableDate {
            get {
                return ResourceManager.GetString("TableDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string TableStatus {
            get {
                return ResourceManager.GetString("TableStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In ähnelt.
        /// </summary>
        internal static string TableCheckIn {
            get {
                return ResourceManager.GetString("TableCheckIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Out ähnelt.
        /// </summary>
        internal static string TableCheckOut {
            get {
                return ResourceManager.GetString("TableCheckOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work ähnelt.
        /// </summary>
        internal static string TableWork {
            get {
                return ResourceManager.GetString("TableWork", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string TablePause {
            get {
                return ResourceManager.GetString("TablePause", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        internal static string TableBalance {
            get {
                return ResourceManager.GetString("TableBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        internal static string ShiftOff {
            get {
                return ResourceManager.GetString("ShiftOff", resourceCulture);
            }
        }

        internal static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }

        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }

        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }

        internal static string DayStatus_Training {
            get {
                return ResourceManager.GetString("DayStatus_Training", resourceCulture);
            }
        }

        internal static string DayStatus_CompensatoryTime {
            get {
                return ResourceManager.GetString("DayStatus_CompensatoryTime", resourceCulture);
            }
        }

        internal static string CalendarCreatedBy {
            get {
                return ResourceManager.GetString("CalendarCreatedBy", resourceCulture);
            }
        }

        internal static string CalendarAutoBreak {
            get {
                return ResourceManager.GetString("CalendarAutoBreak", resourceCulture);
            }
        }

        internal static string ExportFailedMessage {
            get {
                return ResourceManager.GetString("ExportFailedMessage", resourceCulture);
            }
        }

        internal static string SetStatus {
            get {
                return ResourceManager.GetString("SetStatus", resourceCulture);
            }
        }

        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }

        internal static string WorkDaysFormat {
            get {
                return ResourceManager.GetString("WorkDaysFormat", resourceCulture);
            }
        }

        // Rewarded Ads
        internal static string PremiumFeatureTitle {
            get {
                return ResourceManager.GetString("PremiumFeatureTitle", resourceCulture);
            }
        }

        internal static string PremiumFeatureDesc {
            get {
                return ResourceManager.GetString("PremiumFeatureDesc", resourceCulture);
            }
        }

        internal static string WatchVideoOnce {
            get {
                return ResourceManager.GetString("WatchVideoOnce", resourceCulture);
            }
        }

        internal static string AdVideoNotAvailableTitle {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableTitle", resourceCulture);
            }
        }

        internal static string AdVideoNotAvailableMessage {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableMessage", resourceCulture);
            }
        }

        internal static string WarningDailyWorkTimeExceeds {
            get {
                return ResourceManager.GetString("WarningDailyWorkTimeExceeds", resourceCulture);
            }
        }

        internal static string WarningMinPause30 {
            get {
                return ResourceManager.GetString("WarningMinPause30", resourceCulture);
            }
        }

        internal static string WarningMinPause45 {
            get {
                return ResourceManager.GetString("WarningMinPause45", resourceCulture);
            }
        }

        internal static string WarningRestTimeBelowMin {
            get {
                return ResourceManager.GetString("WarningRestTimeBelowMin", resourceCulture);
            }
        }

        internal static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }

        internal static string ExportWorkTimeReport {
            get {
                return ResourceManager.GetString("ExportWorkTimeReport", resourceCulture);
            }
        }

        internal static string ExportTotal {
            get {
                return ResourceManager.GetString("ExportTotal", resourceCulture);
            }
        }

        internal static string ExportYearOverviewTitle {
            get {
                return ResourceManager.GetString("ExportYearOverviewTitle", resourceCulture);
            }
        }

        internal static string HoursShort {
            get {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }

        internal static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }

        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }

        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }

        internal static string AddBreak {
            get {
                return ResourceManager.GetString("AddBreak", resourceCulture);
            }
        }

        internal static string EntryType {
            get {
                return ResourceManager.GetString("EntryType", resourceCulture);
            }
        }

        internal static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }

        internal static string ValidationCheckInOutOrder {
            get {
                return ResourceManager.GetString("ValidationCheckInOutOrder", resourceCulture);
            }
        }

        internal static string ValidationPauseOverlap {
            get {
                return ResourceManager.GetString("ValidationPauseOverlap", resourceCulture);
            }
        }

        internal static string ValidationEndBeforeStart {
            get {
                return ResourceManager.GetString("ValidationEndBeforeStart", resourceCulture);
            }
        }

        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        internal static string ReminderMorningTitle {
            get {
                return ResourceManager.GetString("ReminderMorningTitle", resourceCulture);
            }
        }

        internal static string ReminderMorningBody {
            get {
                return ResourceManager.GetString("ReminderMorningBody", resourceCulture);
            }
        }

        internal static string ReminderEveningTitle {
            get {
                return ResourceManager.GetString("ReminderEveningTitle", resourceCulture);
            }
        }

        internal static string ReminderEveningBody {
            get {
                return ResourceManager.GetString("ReminderEveningBody", resourceCulture);
            }
        }

        internal static string ReminderPauseTitle {
            get {
                return ResourceManager.GetString("ReminderPauseTitle", resourceCulture);
            }
        }

        internal static string ReminderPauseBody {
            get {
                return ResourceManager.GetString("ReminderPauseBody", resourceCulture);
            }
        }

        internal static string ReminderOvertimeTitle {
            get {
                return ResourceManager.GetString("ReminderOvertimeTitle", resourceCulture);
            }
        }

        internal static string ReminderOvertimeBody {
            get {
                return ResourceManager.GetString("ReminderOvertimeBody", resourceCulture);
            }
        }

        internal static string ReminderWeeklyTitle {
            get {
                return ResourceManager.GetString("ReminderWeeklyTitle", resourceCulture);
            }
        }

        internal static string ReminderWeeklyBody {
            get {
                return ResourceManager.GetString("ReminderWeeklyBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time rounding ähnelt.
        /// </summary>
        internal static string TimeRounding {
            get {
                return ResourceManager.GetString("TimeRounding", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string NoRounding {
            get {
                return ResourceManager.GetString("NoRounding", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hourly rate ähnelt.
        /// </summary>
        internal static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today's earnings ähnelt.
        /// </summary>
        internal static string TodayEarnings {
            get {
                return ResourceManager.GetString("TodayEarnings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} min ähnelt.
        /// </summary>
        internal static string MinutesShortFormat {
            get {
                return ResourceManager.GetString("MinutesShortFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press back again to exit ähnelt.
        /// </summary>
        internal static string PressBackAgainToExit {
            get {
                return ResourceManager.GetString("PressBackAgainToExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly goal reached! ähnelt.
        /// </summary>
        internal static string WeekGoalReached {
            get {
                return ResourceManager.GetString("WeekGoalReached", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note: {0} existing days keep their current settings. New settings apply to future days. ähnelt.
        /// </summary>
        internal static string SettingsChangedWarning {
            get {
                return ResourceManager.GetString("SettingsChangedWarning", resourceCulture);
            }
        }

        internal static string AbsenceOverview {
            get {
                return ResourceManager.GetString("AbsenceOverview", resourceCulture);
            }
        }

        internal static string InsightRemainingWeek {
            get {
                return ResourceManager.GetString("InsightRemainingWeek", resourceCulture);
            }
        }

        internal static string InsightMonthTrend {
            get {
                return ResourceManager.GetString("InsightMonthTrend", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CW {0} / {1} ähnelt.
        /// </summary>
        internal static string WeekNumberFormat {
            get {
                return ResourceManager.GetString("WeekNumberFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CW {0} ähnelt.
        /// </summary>
        internal static string WeekNumberShort {
            get {
                return ResourceManager.GetString("WeekNumberShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Estimated end ähnelt.
        /// </summary>
        internal static string EstimatedEnd {
            get {
                return ResourceManager.GetString("EstimatedEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1}:{2:D2} ähnelt.
        /// </summary>
        internal static string RemainingTodayFormat {
            get {
                return ResourceManager.GetString("RemainingTodayFormat", resourceCulture);
            }
        }

        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }

        internal static string BackupExportSuccess {
            get {
                return ResourceManager.GetString("BackupExportSuccess", resourceCulture);
            }
        }

        internal static string BackupExportFailed {
            get {
                return ResourceManager.GetString("BackupExportFailed", resourceCulture);
            }
        }

        internal static string BackupImportSuccess {
            get {
                return ResourceManager.GetString("BackupImportSuccess", resourceCulture);
            }
        }

        internal static string BackupImportFailed {
            get {
                return ResourceManager.GetString("BackupImportFailed", resourceCulture);
            }
        }

        internal static string BackupNoBackupsFound {
            get {
                return ResourceManager.GetString("BackupNoBackupsFound", resourceCulture);
            }
        }

        internal static string ExportBackup {
            get {
                return ResourceManager.GetString("ExportBackup", resourceCulture);
            }
        }

        internal static string ImportBackup {
            get {
                return ResourceManager.GetString("ImportBackup", resourceCulture);
            }
        }

        internal static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }

        internal static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }

        internal static string ExportPdfDesc {
            get {
                return ResourceManager.GetString("ExportPdfDesc", resourceCulture);
            }
        }

        internal static string ExportExcelDesc {
            get {
                return ResourceManager.GetString("ExportExcelDesc", resourceCulture);
            }
        }

        internal static string ExportCsvDesc {
            get {
                return ResourceManager.GetString("ExportCsvDesc", resourceCulture);
            }
        }

        internal static string ExportIcsDesc {
            get {
                return ResourceManager.GetString("ExportIcsDesc", resourceCulture);
            }
        }

        internal static string DayNote {
            get {
                return ResourceManager.GetString("DayNote", resourceCulture);
            }
        }

        internal static string DayNotePlaceholder {
            get {
                return ResourceManager.GetString("DayNotePlaceholder", resourceCulture);
            }
        }

        internal static string CloudBackupNotAvailable {
            get {
                return ResourceManager.GetString("CloudBackupNotAvailable", resourceCulture);
            }
        }

        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }

        internal static string LocalBackup {
            get {
                return ResourceManager.GetString("LocalBackup", resourceCulture);
            }
        }

        internal static string CloudBackup {
            get {
                return ResourceManager.GetString("CloudBackup", resourceCulture);
            }
        }

        internal static string WarningSixMonthAvgExceeds {
            get {
                return ResourceManager.GetString("WarningSixMonthAvgExceeds", resourceCulture);
            }
        }

        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        internal static string BackupImportConfirmText {
            get {
                return ResourceManager.GetString("BackupImportConfirmText", resourceCulture);
            }
        }

        internal static string VacationSkippedWorkedDays {
            get {
                return ResourceManager.GetString("VacationSkippedWorkedDays", resourceCulture);
            }
        }

        internal static string VacationRangeCapped {
            get {
                return ResourceManager.GetString("VacationRangeCapped", resourceCulture);
            }
        }
    }
}

