//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzRechner.Resources.Strings {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanzRechner.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // Rewarded Ads
        internal static string ExportLocked {
            get {
                return ResourceManager.GetString("ExportLocked", resourceCulture);
            }
        }

        internal static string ExportLockedDesc {
            get {
                return ResourceManager.GetString("ExportLockedDesc", resourceCulture);
            }
        }

        internal static string WatchVideoExport {
            get {
                return ResourceManager.GetString("WatchVideoExport", resourceCulture);
            }
        }

        internal static string ExportAdFailed {
            get {
                return ResourceManager.GetString("ExportAdFailed", resourceCulture);
            }
        }

        // Budget Analysis Report
        internal static string BudgetAnalysisTitle {
            get {
                return ResourceManager.GetString("BudgetAnalysisTitle", resourceCulture);
            }
        }

        internal static string BudgetAnalysisDesc {
            get {
                return ResourceManager.GetString("BudgetAnalysisDesc", resourceCulture);
            }
        }

        internal static string MonthlyReport {
            get {
                return ResourceManager.GetString("MonthlyReport", resourceCulture);
            }
        }

        internal static string SavingTip {
            get {
                return ResourceManager.GetString("SavingTip", resourceCulture);
            }
        }

        internal static string ComparedToLastMonth {
            get {
                return ResourceManager.GetString("ComparedToLastMonth", resourceCulture);
            }
        }

        // Extended Stats
        internal static string ExtendedStatsTitle {
            get {
                return ResourceManager.GetString("ExtendedStatsTitle", resourceCulture);
            }
        }

        internal static string ExtendedStatsDesc {
            get {
                return ResourceManager.GetString("ExtendedStatsDesc", resourceCulture);
            }
        }

        internal static string AccessFor24h {
            get {
                return ResourceManager.GetString("AccessFor24h", resourceCulture);
            }
        }

        // Ad nicht verfügbar
        internal static string AdVideoNotAvailableTitle {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableTitle", resourceCulture);
            }
        }

        internal static string AdVideoNotAvailableMessage {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableMessage", resourceCulture);
            }
        }

        // Lade-Fehler
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }

        internal static string LoadErrorExpenses {
            get {
                return ResourceManager.GetString("LoadErrorExpenses", resourceCulture);
            }
        }

        internal static string LoadErrorBudgets {
            get {
                return ResourceManager.GetString("LoadErrorBudgets", resourceCulture);
            }
        }

        internal static string LoadErrorRecurring {
            get {
                return ResourceManager.GetString("LoadErrorRecurring", resourceCulture);
            }
        }

        // Datumsvalidierung
        internal static string ErrorEndDateBeforeStart {
            get {
                return ResourceManager.GetString("ErrorEndDateBeforeStart", resourceCulture);
            }
        }

        // Rechner-Überlauf
        internal static string ErrorOverflow {
            get {
                return ResourceManager.GetString("ErrorOverflow", resourceCulture);
            }
        }

        // "p.a." (pro Jahr) für Rendite-Anzeige
        internal static string PerAnnum {
            get {
                return ResourceManager.GetString("PerAnnum", resourceCulture);
            }
        }

        // PDF-Dokumenttitel
        internal static string FinancialStatistics {
            get {
                return ResourceManager.GetString("FinancialStatistics", resourceCulture);
            }
        }

        // Trend-Anzeige bei fehlenden Vormonatsdaten
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
    }
}
